
spring:
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521:XE
    username: hr2
    password: hr2
    driver-class-name: oracle.jdbc.driver.OracleDriver
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306
#    username: root
#    password: root
#  devtools:
#    livereload:
#      enabled: true
#    restart:
#      enabled: true
#    thymeleaf:
#      cache: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug